library(GOSemSim)
library(parallel)
hsGO2 <- godata('org.Hs.eg.db', keytype = "SYMBOL", ont="BP", computeIC=FALSE)
cl <- makeCluster(92) 
clusterEvalQ(cl,library(GOSemSim))
clusterExport(cl,"drug_targets")
clusterExport(cl,"hsGO2")
go_rs <- parApply(cl,drug_pairs,1,function(x) {pair <- as.vector(x);clusterSim(drug_targets[[pair[1]]], drug_targets[[pair[2]]], semData=hsGO2, measure="Wang", combine="BMA")})
stopCluster(cl) 
drug_pairs_rs <- cbind(drug_pairs,go_rs)
